### PR TITLE
Add thinkfund and city of pa as sponsor

### PR DESCRIPTION
**Pull request by ky28059**
@julia7k

### CODE REVIEW

**Comment by julia7hk** [comment]
should the logo be resized? it looks smaller in comparison to other logos but i am unsure about how to change it.

**Comment by ky28059** [comment]
Perhaps? It's due to the way we do image sizing: each image is scaled down so that its width doesn't exceed `20rem` or its height doesn't exceed `6rem`. Thinkfund just has an annoyingly square logo which messes with things; perhaps the max height can be tweaked?

**Comment by ky28059** [comment]
@julia7k can you also add the city of Palo Alto as a sponsor?

**Comment by ky28059** [comment]
Looks good!

**Pull request merged**
