### PR TITLE
Header tweaks

### PR DESCRIPTION
**Pull request by ky28059**
I wasn't super satisfied with how the current header looks, so I made the black background only show up when scrolled. Thoughts?

### CODE REVIEW

**Comment by ky28059** [comment]
image
image

**Review by saumyasinghal747 — APPROVED** [review]
Looks great, very smooth.

**Comment by ky28059** [comment]
👍 Do you think using `font-light` for the links would look better too?

image
image

**Comment by saumyasinghal747** [comment]
No, I don't think so, it makes it difficult to read without the black background.

**Pull request merged**
